---
# tasks file for duf | EL Family

- name: EL Family | Downloading and installing {{ duf_app }} {{ duf_version }}
  yum:
    name: "{{ duf_el_url }}"
    state: "{{ duf_desired_state }}"
    disable_gpg_check: yes
