---
# tasks file for grype | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading and installing {{ grype_app }} {{ grype_version }}
  ansible.builtin.apt:
    deb: "{{ grype_debian_url }}"
    state: "{{ grype_desired_state }}"
